declare kseries as an s-finite kernel
math-comp/analysis pull request #1004
Opened 2023-08-05 14:48 UTC by affeldt-aist

##### Motivation for this change

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [x] added corresponding documentation in the headers

##### Compatibility with MathComp 2.0

- [x] I added the label `TODO: HB port` to make sure someone ports this PR to
      the `hierarchy-builder` branch **or** I already opened an issue or PR (please cross reference).

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) and put a milestone if possible.

2023-08-06 12:07 UTC, t6s commented
Failed to compile with error messages:
```
File "./classical/cardinality.v", line 1219, characters 0-19:
Error: Cannot apply view card_set_bijP

make[2]: *** [Makefile.coq:830: classical/cardinality.vo] Error 1
make[2]: *** [classical/cardinality.vo] Deleting file 'classical/cardinality.glob'
File "./classical/functions.v", line 2403, characters 5-25:
Error: Cannot apply view subsetP

make[2]: *** [Makefile.coq:830: classical/functions.vo] Error 1
make[2]: *** [classical/functions.vo] Deleting file 'classical/functions.glob'
make[1]: *** [Makefile.coq:409: all] Error 2
```

opam packages are installed as follows:
```
coq                         8.17.0      The Coq Proof Assistant
coq-core                    8.17.0      The Coq Proof Assistant -- Core Binaries and Tools
coq-elpi                    1.17.1      Elpi extension language for Coq
coq-hierarchy-builder       1.4.0       High level commands to declare and evolve a hierarchy based on packed classes
coq-mathcomp-algebra        1.17.0      Mathematical Components Library on Algebra
coq-mathcomp-bigenough      1.0.1       A small library to do epsilon - N reasoning
coq-mathcomp-field          1.17.0      Mathematical Components Library on Fields
coq-mathcomp-fingroup       1.17.0      Mathematical Components Library on finite groups
coq-mathcomp-finmap         1.5.2       Finite sets, finite maps, finitely supported functions
coq-mathcomp-solvable       1.17.0      Mathematical Components Library on finite groups (II)
coq-mathcomp-ssreflect      1.17.0      Small Scale Reflection
coq-stdlib                  8.17.0      The Coq Proof Assistant -- Standard Library
```

2023-08-06 12:14 UTC, t6s commented
Never mind the previous comment. The compilation have somehow succeeded after trying once again.

2023-08-06 13:12 UTC, t6s requested changes
The proof script looks good. The comment in the header is the only thing I want before merging.

I also want some short, additional description of kernels and s-finite kernels in the header, but it would be another PR.

2023-08-07 08:09 UTC, affeldt-aist commented on theories/kernel.v
> +(*                        Kernel and SFiniteKernel.                           *)
Indeed, the doc is a bit succinct. I have added your suggestion and updated the doc.

2023-08-07 11:16 UTC, t6s approved these changes

2023-08-07 11:42 UTC, merged