`setX` -> `setY`; `setM` -> `setX`
math-comp/analysis pull request #1276
Opened 2024-08-01 02:14 UTC by affeldt-aist

##### Motivation for this change

@CohenCyril @t6s @proux01 @Tragicus 

##### Checklist

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [ ] added corresponding documentation in the headers

Reference: [How to document](https://github.com/math-comp/math-comp/wiki/How-to-document)

##### Reminder to reviewers

- Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs)
- Put a milestone if possible
- Check labels

2024-08-01 07:12 UTC, CohenCyril requested changes

2024-08-01 07:12 UTC, CohenCyril commented on CHANGELOG_UNRELEASED.md
> +  + definition `setY`, notation ``` `^` ```
I am also going to argue that `^` generally means exponential and I would rather associate notation ``A `^` B`` to `set_fun A B`. For `setY` maybe we can pick `y` for now?

2024-08-01 07:37 UTC, affeldt-aist commented on CHANGELOG_UNRELEASED.md
> +  + definition `setY`, notation ``` `^` ```
Or ``` `+` ``` ?

2024-08-01 08:02 UTC, proux01 commented on CHANGELOG_UNRELEASED.md
> +  + definition `setY`, notation ``` `^` ```
FWIW, the notation for exclusive or in ssrbool is `_ (+) _`

2024-08-05 09:21 UTC, affeldt-aist commented
I went for ``` `+` ``` because it is shorter. @CohenCyril

2024-08-06 12:17 UTC, merged