minor additions and generalizations
math-comp/analysis pull request #1289
Opened 2024-08-09 03:59 UTC by affeldt-aist

##### Motivation for this change

The lemmas proposed by this PR are slight generalizations (e.g., parameters of `derivable_cst`, `derive_cst` that generalized `derive1_cst`) or lemmas that are specialized variants of
already existing lemmas (e.g., `deriveX_id`, `deriveMr`, `derive_id`). Specialized variants might
look superfluous at first sight but they do save several micro steps in practical examples and
moreover since we have a naming convention (this PR documents it) for the file `derive.v`
these variants are expected results of `Search`. Certainly, there is more to do in this file but
that might already be a useful step.

##### Checklist

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [x] added corresponding documentation in the headers

Reference: [How to document](https://github.com/math-comp/math-comp/wiki/How-to-document)

##### Reminder to reviewers

- Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs)
- Put a milestone if possible
- Check labels

2024-08-09 09:03 UTC, proux01 approved these changes

2024-08-09 09:03 UTC, proux01 commented on theories/derive.v
> +  derivable f x v -> 'D_v (fun x => f x * r) x = (r * 'D_v f x)%R.
Don't we have a notation for that? something like `r \o* f`?

2024-08-09 09:03 UTC, proux01 commented on theories/derive.v
> +  derivable f x v -> 'D_v (fun x => r * f x) x = (r * 'D_v f x)%R.
Maybe
```suggestion
  derivable f x v -> 'D_v (r \*o f) x = (r * 'D_v f x)%R.
```

2024-08-09 09:45 UTC, affeldt-aist commented
Thanks, I totally forgot about this notation.

2024-08-09 09:49 UTC, CohenCyril commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
Why suffix `_id`?

2024-08-09 09:51 UTC, affeldt-aist commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
As a special case of:
```coq
Lemma deriveX f n (x v : V) : derivable f x v ->
  'D_v (f ^+ n.+1) x = (n.+1%:R * f x ^+ n) *: 'D_v f x.
```

2024-08-09 10:04 UTC, CohenCyril commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
https://github.com/math-comp/analysis/blob/5517979929715629bdc5748fdb39ed1083cfab41/theories/normedtype.v#L2460-L2461

2024-08-09 10:46 UTC, CohenCyril commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
This reminds me of `mul_continuous` and `cvgM` (and `continuousM`).
In face these are all equivalent and the bridge is composition.
We should come up with a consistent naming scheme if we are going that way and I do not think `id` is very informative here...

2024-08-09 11:02 UTC, affeldt-aist commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
In `lebesgue_measure.v`, we did that:
```coq
Lemma measurable_exprn D n : measurable_fun D (fun x => x ^+ n).
(* coming first *)

Lemma measurable_fun_pow D f n : measurable_fun D f ->
  measurable_fun D (fun x => f x ^+ n).
(* proved using measurable_comp *)
```

2024-08-09 11:16 UTC, CohenCyril commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
Oh, this is bad... the head symbol's name is `exp` in both case and `pow` is now booked for the power function `R -> R -> R` (which in fairness should probably swapped, but that's a completely different question).
Anyway we should not solve the problem by introducing duplicate names for existing symbols (let's not have `prod` as an alternative for `mul` nor `plus` as an alternative for `add` :wink:), but by finding a uniform naming scheme which encompasses all the cases for continuity, measurability and various notions of derivability.

My suggestion is we align with the conventions for continuity with the following rationale:
- when a lemma is about a composite, like the current `cvgM`, `continuousM`, `deriveX` or `measurable_fun_pow`, we use the single letter suffix (when it exists) as in `cvgM`, `continuousM`, `deriveX`, or `measurableX`
- when a lemma is about applied function, we use the multi-letter prefix instead as in `mul_continuous`, `exp_derive` or `exp_measurable`.

2024-08-09 11:18 UTC, affeldt-aist commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
Note however that we already have:
```coq
Lemma measurableX d1 d2 (T1 : semiRingOfSetsType d1) (T2 : semiRingOfSetsType d2)
    (A : set T1) (B : set T2) :
  measurable A -> measurable B -> measurable (A `*` B).
```

2024-08-09 11:19 UTC, affeldt-aist commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
so, maybe, `measurable_funX` to avoid the conflict?

2024-08-09 11:20 UTC, CohenCyril commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
> so, maybe, `measurable_funX` to avoid the conflict?

Not to avoid the confict, because that's the actual prefix and I did made a mistake (fixed)

2024-08-09 11:23 UTC, affeldt-aist commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
I think that we chose to use `measurable` instead of `measurable_fun` when the suffix suggests a function.

2024-08-09 11:25 UTC, affeldt-aist commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
I guess this shortcut is only acceptable when it does not cause ambiguity, I'll try your proposal fixes asap.

2024-08-09 11:25 UTC, CohenCyril commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
when the prefix is a function name I guess it makes sense indeed

2024-08-10 01:10 UTC, affeldt-aist commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
So maybe use `X` for the cardinal product and `Xn` for `GRing.exp`?

2024-08-11 14:13 UTC, affeldt-aist commented on theories/derive.v
> +  'D_v (@GRing.exp R ^~ n.+1) x = n.+1%:R *: x ^+ n *: v.
(well `funX` is clear enough maybe)

2024-08-13 12:41 UTC, affeldt-aist commented
@CohenCyril ok to merge in the current state?

2024-08-15 13:10 UTC, CohenCyril commented on classical/functions.v
> +Proof. by rewrite mull_funE. Qed.
This is no "elimination" (/definition) lemma (as suggested by suffix `E`), this is a property of symetric bimodules (which function spaces with values in a commutative module R). I would name this `mul_funC`, and keep only one of them.

2024-08-15 13:14 UTC, CohenCyril requested changes
Aside from my (minor) comment. LGTM

2024-08-18 03:36 UTC, merged