expectation of product
math-comp/analysis pull request #1391
Opened 2024-11-13 06:23 UTC by affeldt-aist

##### Motivation for this change

##### Checklist

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [ ] added corresponding documentation in the headers

Reference: [How to document](https://github.com/math-comp/math-comp/wiki/How-to-document)

##### Reminder to reviewers

- Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs)
- Put a milestone if possible
- Check labels

2024-11-15 01:40 UTC, affeldt-aist commented
Maybe it is better to rename `expectation_prod` to `expectation_mul` since the original intent was `expectationM`.

2024-12-03 09:51 UTC, t6s reviewed
I have reviewed lines 0 -- 878 and quickly looked through 879-.
The latter things need some cleaning.

2024-12-03 09:51 UTC, t6s commented on theories/independence.v
> +(* mutual_independence I F == the classes F indexed by I are independent      *)
s/classes/set_systems/

2024-12-03 09:51 UTC, t6s commented on theories/independence.v
> +Lemma g_sigma_algebra_measure_unique142b :
g_sigma_algebra_finite_measure_unique

2024-12-03 09:51 UTC, t6s commented on theories/independence.v
> +Lemma lem142b : forall nu : {finite_measure set T -> \bar R},
This looks like just a rephrasing of the lemma immediately above. Why not use that instead?

2024-12-03 09:51 UTC, t6s commented on theories/independence.v
> +Lemma mutual_independence_finite (I0 : choiceType) (I : {fset I0}%fset)
mutual_independence_fset?

2024-12-03 09:51 UTC, t6s commented on theories/independence.v
> +Lemma g_sigma_algebra_mapping_comp (X : {mfun T >-> R}) (f : R -> R) :
g_sigma_algebra_"preimage", instead of g_sigma_algebra_mapping?

2024-12-03 09:51 UTC, t6s commented on theories/independence.v
> +  independent_RVs P [set: bool] [eta (fun=> cst point) with false |-> X, true |-> Y].
simply if _ then _ else _ ?

2024-12-03 09:51 UTC, t6s commented on theories/independence.v
> +Lemma thm216 (I : set I0) (F : forall i : I0, set (set (T' i)))
independent_RVs_g_preimage, or something like that?

2024-12-03 09:51 UTC, t6s commented on theories/independence.v
> +Lemma thm216 (I : set I0) (F : forall i : I0, set (set (T' i)))
in Klenke, "independent_generators"

2024-12-03 09:51 UTC, t6s commented on theories/independence.v
> +Lemma measurable_fun_prod d [T : measurableType d] [R : realType] [D : set T] [I : eqType]
measurable_prod?

2024-12-06 02:52 UTC, affeldt-aist commented on theories/independence.v
> +Lemma g_sigma_algebra_mapping_comp (X : {mfun T >-> R}) (f : R -> R) :
What about `g_sigma_algebra_fun` for the sigma-algebra generated by one function? (this is also sometimes called pull-back sigma-algebra but I am not sure this terminology makes up for easily searchable names)

2025-01-10 14:23 UTC, affeldt-aist commented on theories/independence.v
> +Lemma g_sigma_algebra_mapping_comp (X : {mfun T >-> R}) (f : R -> R) :
Let's go with `preimage`

2025-02-25 05:51 UTC, affeldt-aist commented on theories/probability.v
> +Lemma g_sigma_algebra_mapping_comp (X : {mfun T >-> R}) (f : R -> R) :
This should be generalized.

2026-01-05 08:35 UTC, t6s commented
I forgot the context for this draft PR.  What is the current status?

2026-01-05 10:10 UTC, affeldt-aist commented
> I forgot the context for this draft PR. What is the current status?

Rebased but for reasons I forgot some things look duplicated in `probability.v` and `independence.v`.
If I remember correctly, we introduced definitions of independence following Klenke's book and
were able to reproduce a few, non-trivial lemmas.
What about we remove duplications and PR only an `independence.v` file with what we have so far?
(That would save me the trouble of regular rebasings and certainly these definitions will be wanted at some point.)

2026-01-06 04:17 UTC, affeldt-aist commented
I removed duplicates and unused lemmas and did some cleaning.
@t6s About the status: I think that this PR is really proposing definitions and justifying them with standard theorems from the literature.
If one finds it useful to have these definitions in master we can maybe think of merging at some point after review with some "experimental" proviso in the header file (like we did in the past for `probability.v`).
What do you think @hoheinzollern ?
fyi: @CohenCyril @proux01

2026-01-06 06:51 UTC, t6s commented on theories/probability.v
> +    (measurableT_comp (@normr_measurable _ _) (@measurable_funPT _ _ _ _ f)).
This `HB.instance` is not adding a new instance, and the intended instance already exists:
```
Check fun f : {mfun aT >-> rT} => @normr _ _ \o f : {mfun _ >-> _}.  
```
this succeeds anyway.

2026-01-06 06:56 UTC, t6s commented on theories/numfun.v
> +Qed.
I suggest renaming
- `funr_normr` -> `funrposDneg_norm`
- `funrposneg` -> `funrposBneg`

Also the latter can be stated in the form `f = f^\+ \+ f^\-`, subsuming the next lemma.

2026-01-06 06:58 UTC, t6s commented on theories/numfun.v
> +Qed.
This lemma should be removed as it is just an instance of `funrposneg` above.

2026-01-06 06:59 UTC, t6s commented on theories/numfun.v
> +Lemma funrD_posD f g : f \+ g = (f^\+ \+ g^\+) \- (f^\- \+ g^\-).
This one, on the other hand, is nontrivial and should be kept.

2026-01-06 07:00 UTC, t6s commented on theories/numfun.v
> +Lemma funrD_posD f g : f \+ g = (f^\+ \+ g^\+) \- (f^\- \+ g^\-).
But the name looks bad and I have no good suggestion for now.

2026-01-06 07:05 UTC, t6s requested changes
> I have reviewed lines 0 -- 878 and quickly looked through 879-. The latter things need some cleaning.

It looks like I reviewed `independence.v` once, and the file looks not so bad. @hoheinzollern can you double check?

I have read the other files and put some comments requesting some changes.

2026-01-06 07:32 UTC, t6s commented on theories/numfun.v
> +Lemma funrD_posD f g : f \+ g = (f^\+ \+ g^\+) \- (f^\- \+ g^\-).
`funrD_posBneg` would be better.

This can be seen as a form of distributivity where `^\+` and `^\-` parallelly distributes over `\+` inside
expressions of the form `_^\+ \- _^\-`.  I do not know how to name it.

2026-01-06 09:58 UTC, affeldt-aist commented on theories/probability.v
> +    (measurableT_comp (@normr_measurable _ _) (@measurable_funPT _ _ _ _ f)).
And moreover this section has nothing to do here, thanks.

2026-01-06 10:00 UTC, affeldt-aist commented on theories/numfun.v
> +Qed.
With this naming it is maybe better to reverse the equality to have the more complicated expression on the left, and then we can maybe drop the `_norm` suffix.

2026-01-06 11:05 UTC, t6s commented on theories/numfun.v
> +Qed.
that's better

2026-01-06 14:43 UTC, affeldt-aist commented on theories/numfun.v
> +Lemma funrD_posD f g : f \+ g = (f^\+ \+ g^\+) \- (f^\- \+ g^\-).
In fact this lemma has a short proof once one observes that it almost corresponds to `interchange` with addition _and_ subtraction (most if not all uses of `interchange` in MathComp use twice the same operator). `interchange` lemmas are suffixed with `ACA` like `addrACA` but that might be an overkill here to abide by this naming scheme because we mix two operators and moreover on functions (calling for a `fctE` suffix) so maybe `addBr` could be enough to suggests `interchange sub add` and therefore the name could just be `funrDB` (and `funeDB` for the corresponding lemmas for extended real numbers).

2026-01-06 14:45 UTC, affeldt-aist commented
> I have read the other files and put some comments requesting some changes.

Thanks for the comments that triggered very welcomed improvements.

2026-01-06 15:37 UTC, t6s commented on theories/numfun.v
> +Lemma funrD_posD f g : f \+ g = (f^\+ \+ g^\+) \- (f^\- \+ g^\-).
`interchange` is indeed another structure involved here, and I also thought about incorporating `ACA` in its name, though not coming up with a tidy result. 

`funrDB` is neat but looks a bit too stripped off since it does not clearly indicate that it is about `^+` and `^-`.
I am however not sure how to restore that info without elongating the name, and weakly approving `funrDB`.

2026-01-06 17:07 UTC, CohenCyril commented on theories/independence.v
> +  (forall i, I i -> measurable (E i)) /\
why is measurability built in independence of variables? I would have expected measurability to be a side condition. (Same remark in each definition below)

2026-02-26 00:58 UTC, affeldt-aist commented
(I just made a rebase on master, hence the push force)

2026-03-03 00:50 UTC, affeldt-aist commented on theories/independence.v
> +  (forall i, I i -> measurable (E i)) /\
You mean like having the assumption of measurability be one of the parameters of `independent_events` or like having no `measurability` in the definition at all and instead having it appearing as an hypothesis of lemmas of independence?

2026-03-03 20:12 UTC, CohenCyril commented on theories/independence.v
> +  (forall i, I i -> measurable (E i)) /\
Either

2026-04-22 14:06 UTC, affeldt-aist commented on theories/probability.v
> +Lemma g_sigma_algebra_mapping_comp (X : {mfun T >-> R}) (f : R -> R) :
Done.

2026-04-22 14:11 UTC, affeldt-aist commented
@t6s I have rebased, cleaned up the proofs, since a few things have been introduced into master since, I could eliminate duplicates. Several files are touched but that is because this PR led us to simplify lemmas about `fun{r,e}pos` and `fun{r,e}neg`. @CohenCyril The measurability conditions in the definitions of independence have been removed and kept only in the lemmas that do require them.

What about we merge? (as a step towards completion of [issue 1808](https://github.com/math-comp/analysis/issues/1808))

2026-04-23 06:12 UTC, affeldt-aist commented
(CI green at last)

2026-04-24 01:38 UTC, t6s approved these changes
My comments are all resolved and the code looks tidy enough. Looks good to me.

2026-04-24 01:39 UTC, merged