differentiation under integral
math-comp/analysis pull request #1435
Opened 2024-12-16 15:18 UTC by affeldt-aist

##### Motivation for this change

this can certainly be generalized but this version has already been used to prove the Gauss integral so it is maybe worth having anyway

##### Checklist

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`

~~- [ ] added corresponding documentation in the headers~~

Reference: [How to document](https://github.com/math-comp/math-comp/wiki/How-to-document)

##### Reminder to reviewers

- Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs)
- Put a milestone if possible
- Check labels

2024-12-17 22:21 UTC, CohenCyril commented on theories/normedtype.v
> +Lemma cvgr_sub0 f a : (fun x => f x - a) @ F --> 0 <-> f @ F --> a.
I don't understand the naming of this lemma.

2024-12-18 03:26 UTC, affeldt-aist commented on theories/normedtype.v
> +Lemma cvgr_sub0 f a : (fun x => f x - a) @ F --> 0 <-> f @ F --> a.
I think that it was named after:
```coq
cvge_sub0 : forall {I : Type} {F : set_system I}, Filter F ->
forall {R : realFieldType} (f : I -> \bar R) [k : \bar R],
k \is a fin_num -> (f x - k)%E @[x --> F] --> 0 <-> f x @[x --> F] --> k
```
What about `cvg_zeroP`? Since it is like `cvg_zero` but going in both directions.

2024-12-18 04:40 UTC, affeldt-aist commented
I have added the gauss integral as an application of differentiation under integral

2024-12-18 22:28 UTC, CohenCyril commented on theories/normedtype.v
> +Lemma cvgr_sub0 f a : (fun x => f x - a) @ F --> 0 <-> f @ F --> a.
Following the convention of `subr_eq0` the latter should be `sube_cvg0`, and the former `subr_cvg0`

2025-01-10 00:40 UTC, affeldt-aist commented
@IshiguroYoshihiro do you have improvements to propose?

2025-01-17 13:37 UTC, affeldt-aist commented
ping? :-)

2025-01-19 16:41 UTC, CohenCyril commented on theories/ftc.v
> +(*                      f has type R -> T -> R for R : realType               *)
This looks very specific... maybe make the notation local, and name it partial1of2 or something like that ?

2025-01-19 16:42 UTC, CohenCyril commented on theories/gauss_integral.v
> +#[global] Hint Extern 0 (oneDsqr _ != 0)%R => solve[apply: oneDsqr_ge1] : core.
This could be integrated as part an instance of posnum.

2025-01-19 16:43 UTC, CohenCyril commented on theories/gauss_integral.v
> +Definition gauss (x : R) := expR (- x ^+ 2).
`gauss_fun` ? or `gauss_distribution` ?

2025-01-19 16:45 UTC, CohenCyril commented on theories/gauss_integral.v
> +  \int[mu]_(x in `[0%R, +oo[) gauss x = Num.sqrt pi / 2.
```suggestion
Lemma integral0y_gauss :
  \int[mu]_(x in `[0%R, +oo[) gauss x = Num.sqrt pi / 2.
```

2025-01-19 16:47 UTC, CohenCyril commented on theories/lebesgue_integral.v
> +Proof.
```suggestion
Lemma ge0_cvgn_integral :
  \int[mu]_(x in `[0%R, n%:R]) (f x)%:E @[n --> \oo] -->
  \int[mu]_(x in `[0%R, +oo[) (f x)%:E.
Proof.
```

2025-02-05 01:51 UTC, affeldt-aist commented on theories/gauss_integral.v
> +Definition gauss (x : R) := expR (- x ^+ 2).
`gauss_fun` looks better to me, `distribution` might suggest it is already equipped with structures from `probability.v`

2025-02-05 03:06 UTC, affeldt-aist commented on theories/gauss_integral.v
> +#[global] Hint Extern 0 (oneDsqr _ != 0)%R => solve[apply: oneDsqr_ge1] : core.
I replace the 1st, 2nd, and 3rd hints (the last one was wrong moreover) and added instead
```
Lemma oneDsqr_gt0_subproof x : Signed.spec 0 !=0 >=0 (oneDsqr x).
Proof. by rewrite /= oneDsqr_neq0/= oneDsqr_ge0. Qed.

Canonical oneDsqr_ge0_snum x := Signed.mk (oneDsqr_gt0_subproof x).
```

2025-02-05 03:07 UTC, affeldt-aist commented on theories/ftc.v
> +(*                      f has type R -> T -> R for R : realType               *)
Renamed *and* made local.

2025-02-05 12:46 UTC, affeldt-aist commented
@CohenCyril CI's green

2025-02-05 12:50 UTC, affeldt-aist commented on theories/gauss_integral.v
> +#[global] Hint Extern 0 (oneDsqr _ != 0)%R => solve[apply: oneDsqr_ge1] : core.
Indeed, these Hints were not triggered at all. I checked that the posnum is indeed effective (it actually discharges goals that were proved previously by direct invokations). I only kept the one not covered by posnum with the is_true coercion explicit (see the last commit).

2025-02-05 13:01 UTC, affeldt-aist commented
ah, forgot to put `ge0_cvgn_integral` in the changelog, one sec

2025-02-05 14:09 UTC, CohenCyril requested changes
Wait a sec

2025-02-05 14:12 UTC, CohenCyril approved these changes

2025-02-06 00:57 UTC, affeldt-aist commented
Many thanks for the careful review!

2025-02-06 00:57 UTC, merged