Mathcom master pseudo normed zmod
math-comp/analysis pull request #180
Opened 2020-04-14 09:45 UTC by mkerjean

Further generalisations from normedModTypes to PseudoMetricNormedZmodTypes.

2020-04-14 09:58 UTC, mkerjean commented
Issue: Sometimes one needs to explicitly mention the pseudoMetricNormedZmodType on which lemmas are applied while it was not necessary with NormedModTypes. It also makes (at least) `derive.v` fail ([here](https://github.com/math-comp/analysis/blob/3085f787d0d16b08db4a151b711382de9fabe87e/theories/derive.v#L786) view locally_le_locally_norm can't be applied). What's missing ?

2020-04-14 12:48 UTC, mkerjean commented
Issue: Some further generalizations should be possible but `lim` does not seem to work on `PseudoNormedZmodule`. See  [here](https://github.com/math-comp/analysis/blob/0eb77159595dc65f63f4e5ce955303eb74d88a14/theories/normedtype.v#L789).

2020-04-14 20:32 UTC, affeldt-aist commented on theories/normedtype.v
> +Proof. by move=> Fx Fy; rewrite -closeE; apply: (@flim_close _ V). Qed.
I observe that `apply: flim_close` concludes the proof provided `F` is declared as `F : set (set V)`. Also `flim_unique` is generalized at the level of topological spaces by PR #177 so that the problem should disappear after a rebase.

2020-04-14 20:33 UTC, affeldt-aist commented on theories/normedtype.v
> +Proof. by rewrite -closeE; apply:  (@flim_close _ V). Qed.
Here also the problem should disappear with PR #177 that generalized `locally_flim_unique`.

2020-04-14 20:33 UTC, affeldt-aist commented on theories/normedtype.v
> +Proof. by move=> Fl; have Fcv := cvgP Fl; apply: (@flim_unique _ V F). Qed.
Here also the problem should disappear with PR #177 that generalized `flim_lim`.

2020-04-14 20:34 UTC, affeldt-aist commented on theories/normedtype.v
>  Proof.
Naturally `Proof. exact: pseudoMetricNormedZModType_hausdorff. Qed.`

2020-04-15 07:31 UTC, mkerjean commented on theories/normedtype.v
> +Proof. by move=> Fx Fy; rewrite -closeE; apply: (@flim_close _ V). Qed.
Would that solve also the generalization to [Section NormedModule_numFieldType](https://github.com/math-comp/analysis/blob/0eb77159595dc65f63f4e5ce955303eb74d88a14/theories/normedtype.v#L786), mentioned previously ?

2020-04-15 08:05 UTC, mkerjean commented on theories/normedtype.v
> +Proof. by move=> Fx Fy; rewrite -closeE; apply: (@flim_close _ V). Qed.
It seems rather related to PR #90.

2020-04-23 15:55 UTC, affeldt-aist commented
This branch/PR has been rebased on PR #177 that lifts several lemmas about limits to the level of topological spaces, thus the issues about `flim_lim` and `flim_unique` have disappeared. But similar inference problems seem to occur later, e.g., here https://github.com/math-comp/analysis/blob/b8c628cb71191eeb9e5d600c0ea9c10dcedf2241/theories/derive.v#L786 .

2020-05-21 13:14 UTC, affeldt-aist commented
There are still notation issues with lemmas [`norm_lim_id`](https://github.com/math-comp/analysis/blob/55b94bdc2d7ae32f61ff031ab9267ce9c2c63dbe/theories/normedtype.v#L1208) and [`norm_cvg_lim`](https://github.com/math-comp/analysis/blob/55b94bdc2d7ae32f61ff031ab9267ce9c2c63dbe/theories/normedtype.v#L1210).

There are still generalizations to do, at least about the lemmas related to the new `bounded_on` predicate, but also some generalizations for which I might have screwed up when rebasing. :-/

2020-06-17 21:51 UTC, affeldt-aist commented
FYI, I rebased on top of a recent master (with PR #230) and at first sight the behavior seems unchanged, i.e.:
- in `normedtype.v`:
  + `norm_cvg_eq` -> still requires explicit type
  + `norm_lim_id` -> still requires `[lim ... in ...]` notation
  + `norm_cvg_lim` -> still requires explicit type and `[lim ... in ...]` notation
  + `continuous_cvg_dist` -> still requires explicit type
- in `derive.v`:
  + `bilinear_eqo` -> still requires explicit `[pseudoMetricNormedZmodType R of _]`
  + `dinv` -> still requires explicit `[pseudoMetricNormedZmodType R of _]`

2021-03-26 14:34 UTC, mkerjean commented
> FYI, I rebased on top of a recent master (with PR #230) and at first sight the behavior seems unchanged, i.e.:
> 
>     * in `normedtype.v`:
>       
>       * `norm_cvg_eq` -> still requires explicit type
>       * `norm_lim_id` -> still requires `[lim ... in ...]` notation
>       * `norm_cvg_lim` -> still requires explicit type and `[lim ... in ...]` notation
>       * `continuous_cvg_dist` -> still requires explicit type
> 
>     * in `derive.v`:
>       
>       * `bilinear_eqo` -> still requires explicit `[pseudoMetricNormedZmodType R of _]`
>       * `dinv` -> still requires explicit `[pseudoMetricNormedZmodType R of _]`

In `normedtype.v`:
* explicit argument [l.1793](https://github.com/math-comp/analysis/blob/1c5946eec37e3ab923fb60de41b5f84e1f435a3a/theories/normedtype.v#L1793) explicit argument needed for `cvg_ball` (not needed in the case of `V : normedType R`).

2021-03-26 15:02 UTC, mkerjean commented
There is still an admit in `derive.v`. We should understans why explicit argument are needed for `pseudoMetricNormedZmodType ` while they are not needed for `normedType`.

2021-05-29 09:10 UTC, affeldt-aist commented
Does https://github.com/math-comp/analysis/pull/180/commits/06dcf7fddfb08b4832056da2f6db44ff0711e2fe
really fix the inference problem derive.v? Or does it just narrow it?

2021-05-29 14:24 UTC, affeldt-aist commented on theories/normedtype.v
> +Section PseudoNormedZmod_numDomainType. (* to be lifted *)
What does this comment mean?

2021-05-29 14:33 UTC, affeldt-aist commented on theories/normedtype.v
> +Lemma norm_lim_id x : [lim x in V](*NB: was lim x*) = x. Proof. exact: lim_id. Qed.
I guess this is now the main concern of this PR. This notation is properly documented, so this is acceptable to me as long as we keep the comment. @CohenCyril Is this acceptable for you too? Does the modification made to `nbhs_le_nbhs_norm` ring any bell by any chance?

2021-05-29 14:34 UTC, affeldt-aist requested changes
Improve one comment and confirm the notation use with another reviewer (see the conversation).

2021-06-01 07:28 UTC, mkerjean commented on theories/normedtype.v
> +Section PseudoNormedZmod_numDomainType. (* to be lifted *)
No idea ... I guess it can be deleted.

2021-07-22 06:51 UTC, affeldt-aist approved these changes
ok with me but I am biased

2021-07-22 08:08 UTC, CohenCyril commented on theories/normedtype.v
> +  \forall M \near +oo, M \is Num.real /\ \forall y' \near F, `|y'| < M.
```suggestion
  \forall M \near +oo, \forall y' \near F, `|y'| < M.
```
Indeed `\forall M \near +oo, M \is Num.real` is always true and could be added after `nbhs_pinfty_ge` and proved using it.

2021-07-22 08:08 UTC, CohenCyril commented on theories/normedtype.v
> +move/(cvg_ball (y := l)): xl=> /(_ _ a)/nbhs_ballP[_/posnumP[b]]; apply; exact: ballxx.
do not use the `_ := _` syntax, it is too unstable.

2021-07-22 08:10 UTC, CohenCyril requested changes
Ready to merge after my comments have been taken into account.
Also, I would rather have TODO/NBs turned into issues, they are less prone to bitrot.

2021-07-26 05:54 UTC, affeldt-aist commented on theories/normedtype.v
> +move/(cvg_ball (y := l)): xl=> /(_ _ a)/nbhs_ballP[_/posnumP[b]]; apply; exact: ballxx.
It looks like this actually revealed a wrong definition: https://github.com/math-comp/analysis/pull/180/commits/13e50e4d44025ed09686f97ea1f2bb0286ad15d8

2021-07-26 06:59 UTC, affeldt-aist commented
> Ready to merge after my comments have been taken into account.
> Also, I would rather have TODO/NBs turned into issues, they are less prone to bitrot.

NBs that were marking issues caused by this PR has been resolved (I think).
There are still TODOs but I think that they predates this PR.
Ok to merge and chase TODOs later?

2021-07-26 07:07 UTC, affeldt-aist commented on theories/normedtype.v
> +Lemma norm_lim_id x : [lim x in V](*NB: was lim x*) = x. Proof. exact: lim_id. Qed.
solved by https://github.com/math-comp/analysis/pull/180/commits/8443585e56a0cfcb0173b9ff4ea32681b66c4ecc actually...

2021-07-27 22:20 UTC, CohenCyril approved these changes

2021-07-27 22:22 UTC, merged