Add a distrLattice canonical structure to set T.
math-comp/analysis pull request #206
Opened 2020-05-18 21:11 UTC by vlj

Hi,

This add a canonical distrLattice structure to setT and subset relation.
I have far less experience in adding a canonical structure than I have writing lemma so the PR is likely a bit rough, any guidance is appreciated.

Some comments:
- For some reasons coq fails to unify the type of the lemma setU setI ... when passed as argument to MeetJoinMixin. I added "wrapper lemma" SetOrder_setCI SetOrder_setCU ... to force the type. I'm not sure this is the right thing to do (I could also use @setU (set T) directly in the argument but it would be quite hard to read) and the naming is maybe wrong.
- subset is a Prop while distrLattice expects a rel (ie result type is bool). I wrapped the subset relation in asboolsubset. This means that to use lemma in order (like in my case ltux) one need to map subset and asboolsubset forth and back so I provided subsetE. I don't know if it's the usual idiom.

2020-05-19 16:47 UTC, CohenCyril commented
Hi @vlj thanks for your contribution, I will take a look a deeper look next week.

2020-08-07 22:02 UTC, CohenCyril commented
@vlj  thanks for your contribution, I think once the proofs are tidied we can merge, indeed proofs in math-comp/analysis should adhere to [math-comp core contributing style](https://github.com/math-comp/math-comp/blob/master/CONTRIBUTING.md) and more particularily [the proof style](https://github.com/math-comp/math-comp/blob/master/CONTRIBUTING.md#proof-style).
In particular:
- The only period symbol (`.`) in a line should be the last character of the line.
- When exactly two subgoals are generated, the first one should be indented and second one should not. No bullets should be used.
Sorry for the delay, and please do not hesitate to ask questions, I will try to be more reactive now!

2020-08-24 11:53 UTC, CohenCyril commented
> About the first convention is it accepted to use the semicolon symbol even if only a single goal is focused?

Yes, in mathcomp proof style conventions, the semicolon is not used regardless of how many goals are focused, and its purpose is to group tactics in a line that makes a single, substantial step of reasoning.

2020-08-24 11:55 UTC, CohenCyril commented on theories/classical_sets.v
> +split.
These three last lines should be regrouped in one single line.

2020-08-24 12:36 UTC, CohenCyril commented
Hi @vlj, I refactored and cleaned your code. The wrapper lemmas you defined were not necessary if you partially apply the wanted lemmas. Some intermediate definitions were superfluous. About the `bool` vs `Prop` thing, it is indeed expected that lattice relations are in `bool` while the classic subset relation is in `Prop`. Indeed `asbool` was needed but should be used minimally.
Some pieces of code are still missing to turn sets into a full-fledged distributive lattice with top and bottom and complement. We could merge as such and open a new PR to complement it...
From the naming of your (former) wrapper lemmas, I also suspect that many of our set lemmas in `classical_sets.v` are not following the naming conventions from `finset.v` or `order.v` (also cf #252), hence one should open yet another PR to fix them. (ping @affeldt-aist)

2020-08-25 01:07 UTC, affeldt-aist commented
`setIDl` was renamed to `setIUl` by a recent PR (hence the rebase/push force).
`classical_sets.v` was lacking `setUK`, etc. lemmas.
Should `setI_meet` be renamed `setIidPlE` and moved near `setIidPl`?

2020-08-26 18:40 UTC, vlj commented
Thanks for the refactoring and renaming !
I added the canonical structure for top and bottom. I didn't manage to get Order.BLattice.Mixin to accept the sub0set lemma so I introduced an intermediate fact that uses the asboolP. There is no counterpart for the setTsub so I directly write the one that fits the input of Order.TBLattice.Mixin.

2020-09-12 21:49 UTC, vlj commented
I added complement and sub.

2020-09-25 11:45 UTC, CohenCyril requested changes
The `Exports` module misses a few canonicals: `Internal.blatticeType` ... `Internal.ctbDistrLatticeType`. Also, I think `subEset` should be renamed `subsetEset`, and you should add as well ``properEset : (X < Y)%O = (X `<` Y)``, ``subEset : (X `\` Y)%O = (X `\` Y)``, ``complEset : (~` X)%O = ~` X``, ``botEset : 0%O = set0`` , ``topEset : 1%O = setT``.

2020-09-25 12:17 UTC, CohenCyril commented
Additionally, the changelog should document the new canonical instances and the `E` lemmas.

2020-09-26 15:33 UTC, vlj commented
I merged and added the lemmas suggested.

2020-09-26 19:17 UTC, CohenCyril commented
Great! Can you squash and rebase?

2020-09-26 19:17 UTC, CohenCyril commented on CHANGELOG_UNRELEASED.md
> +  + Canonical `porderType`, `latticeType`, `distrLatticeType`, `blatticeType`, `tblatticeType`, `bDistrLatticeType`, `tbDistrLatticeType`, `cbDistrLatticeType`, `ctbDistrLatticeType`.
```suggestion
  + Canonical `porderType`, `latticeType`, `distrLatticeType`, `blatticeType`, `tblatticeType`, `bDistrLatticeType`, `tbDistrLatticeType`, `cbDistrLatticeType`, `ctbDistrLatticeType` on classical `set`
```

2020-09-26 19:20 UTC, CohenCyril commented on theories/classical_sets.v
> +Definition proper_subset {A} (X Y : set A) := (Y != X) && `[< subset X Y >].
```suggestion
Definition proper_subset {A} (X Y : set A) := (Y != X)  /\ X `<=` Y.
```

2020-09-26 22:12 UTC, CohenCyril commented on theories/classical_sets.v
> +Definition proper_subset {A} (X Y : set A) := (Y != X) /\ X `<=` Y.
Actually, on second thoughts, this definition would be even more usable like this:
```suggestion
Definition proper_subset {A} (X Y : set A) := (X `<=` Y) /\ (exists2 a, Y a & ~ X a).
```
With lemma ``proper_neqAsubset :  (X `<` Y) =  (X `!=` Y) /\  (X `<=` Y)``

2020-09-28 20:41 UTC, vlj commented
Working on it, but it's WIP.

2020-09-29 11:46 UTC, vlj commented
Is mathcomp analysis supposed to be built against dev branch of mathcomp ? I need the contra_not_neq lemma which seems to have been introduced recently in ssrbool.

2020-09-29 11:53 UTC, CohenCyril commented
Indeed, @vlj we build master against stable releases, you may add it in `boolp.v` as long as you open an issue after the merge of the PR to remind us to remove it as soon as we switch to mathcomp 1.12 when it is release

2020-09-30 12:45 UTC, vlj commented
I modified the proper_subset definition. I had some troubles writing the properEset and I'm not sure it's the easiest way to do ; it uses a couple intermediate lemma, setDset0 :  (Y `\` X) != set0 <-> exists2 a : T, Y a & ~ X a. and subsetNeqSetDnonempty (H : X `<=` Y) : X != Y <-> (Y `\` X) != set0. I think setDset0 may be useful for other purpose, I don't know if subsetNeqSetDnonempty  is too specific or not. I'm also not very experimented with the asbool_* lemmas so maybe it's not optimal either.

2020-10-04 10:48 UTC, vlj commented
Added proper_neqAsubset lemma.

2020-11-05 01:38 UTC, affeldt-aist commented
> The `Exports` module misses a few canonicals: `Internal.blatticeType` ... `Internal.ctbDistrLatticeType`. Also, I think `subEset` should be renamed `subsetEset`, and you should add as well `` properEset : (X < Y)%O = (X `<` Y) ``, `` subEset : (X `\` Y)%O = (X `\` Y) ``, `` complEset : (~` X)%O = ~` X ``, `botEset : 0%O = set0` , `topEset : 1%O = setT`.

It looks like these changes have been performed.

2020-11-05 03:05 UTC, affeldt-aist commented on theories/classical_sets.v
> +Definition proper_subset {A} (X Y : set A) := (Y != X) /\ X `<=` Y.
I tried yet another definition, the one mimicking `fintype`. See the last commit.

2020-11-05 11:04 UTC, pi8027 commented
@affeldt-aist Could you request me a review here just not to forget about it? Thanks.

2020-11-05 11:06 UTC, affeldt-aist commented
> @affeldt-aist Could you request me a review here just not to forget about it? Thanks.

Sure. Thank you!

2020-11-06 10:08 UTC, pi8027 commented on theories/classical_sets.v
> +  SetOrder_joinKI SetOrder_meetKU (@setIUl _) setIid.
I think it is better to make `Order.lt` convertible with `(fun X Y => `[<X `<` Y>])` here. The third argument of `MeetJoinMixin` has to be explicitly provided and `(fun _ _ => erefl)` has also to be replaced.

2020-11-06 10:08 UTC, pi8027 commented on theories/classical_sets.v
> +Local Canonical blatticeType :=
```suggestion
Local Canonical bLatticeType :=
```

2020-11-06 10:08 UTC, pi8027 commented on theories/classical_sets.v
> +Local Canonical tblatticeType :=
```suggestion
Local Canonical tbLatticeType :=
```

2020-11-06 10:57 UTC, affeldt-aist commented on theories/classical_sets.v
> +Notation "A `<` B" := (proper A B) : classical_set_scope.
Indeed. But maybe this should be another PR. Is it ok to raise an issue about that and do it later, or do you think it should be done now?

2020-11-06 15:23 UTC, pi8027 commented on theories/classical_sets.v
> +Notation "A `<` B" := (proper A B) : classical_set_scope.
It is OK to do so, but I think ssrmatching becomes less useful when we duplicate definitions like this, and then we often have to rewrite ones to others manually. Also, there is a substantial overlap between the order theory and `classical_sets.v`.

2020-11-08 00:12 UTC, CohenCyril commented on theories/classical_sets.v
> +Notation "A `<` B" := (proper A B) : classical_set_scope.
@pi8027 in fact, it still makes a difference even in mathcomp analysis: because the propositional version is directly usable as an implication (for `subset`) or a conjunction of an implication (and a negation of one) for `proper`, we should have both, and there should be a reflection lemma between the two.
However, the big problem form is the naming, which conflicts entirely with finset, ... we should rename them all, but that's beyond the scope of this PR.

2020-11-09 09:01 UTC, affeldt-aist commented on theories/classical_sets.v
> +Notation "A `<` B" := (proper A B) : classical_set_scope.
> there should be a reflection lemma between the two

Are the `subsetEset`, `properEset`, etc. lemmas sufficient for this purpose? (Provided we `Export SetOrder.Exports.`.)

2020-11-10 14:27 UTC, CohenCyril approved these changes
LGTM now!

2020-11-10 14:27 UTC, merged