Closed ball
math-comp/analysis pull request #283
Opened 2020-11-16 20:01 UTC by mkerjean

A theory of closed balls.

2020-12-04 11:26 UTC, affeldt-aist commented
note that PR #268 has been merged so that you can get rid of a few lemmas about closure after rebasing

2020-12-08 17:09 UTC, CohenCyril commented on theories/normedtype.v
> +move=> x0; rewrite normmZ normrV ?unitfE ?normr_eq0 //=.
using `normfV` will radically simplify this proof.

2020-12-08 17:09 UTC, CohenCyril commented on theories/normedtype.v
> +move=> x0; rewrite normmZ normrV ?unitfE ?normr_eq0 //=.
Please use `f`-suffixed lemmas rather than `r`-suffixed lemma when you have a field, it can only lead to shorter and clearer proofs.

2020-12-08 17:11 UTC, mkerjean commented on theories/normedtype.v
> +move=> x0; rewrite normmZ normrV ?unitfE ?normr_eq0 //=.
That's what I was looking for thanks, I will delete `normrZV`.

2020-12-08 17:13 UTC, CohenCyril commented on theories/normedtype.v
> +move=> x0; rewrite normmZ normrV ?unitfE ?normr_eq0 //=.
You can keep the lemma, and move it to the theory of `normedModType`, with the one-line-proof.

2020-12-08 17:13 UTC, CohenCyril commented on theories/normedtype.v
> +Lemma closure_ballE (R : realFieldType) (V : normedModType R) (x : V)
I suggest
```suggestion
Lemma closed_ballE (R : realFieldType) (V : normedModType R) (x : V)
```

2020-12-08 17:14 UTC, CohenCyril commented on theories/normedtype.v
> +Lemma closed_closed_ball (R : realFieldType) (V : normedModType R) (x : V)
```suggestion
Lemma closed_ball_closed (R : realFieldType) (V : normedModType R) (x : V)
```
The convention we try to enforce is lemma ending with a unary predicate are named with this predicate as a suffix.

2020-12-08 17:16 UTC, CohenCyril commented on theories/normedtype.v
> +Lemma ball_closed_ball (R : numDomainType) (V : pseudoMetricType R) (x : V)
I suggest the name
```suggestion
Lemma `sub_closed_ball` (R : numDomainType) (V : pseudoMetricType R) (x : V)
```

2020-12-08 17:16 UTC, CohenCyril commented on theories/normedtype.v
> +Lemma closed_ball_ball (R : realFieldType) (M : normedModType R) (x : M)
```suggestion
Lemma sub_closed_ball (R : realFieldType) (M : normedModType R) (x : M)
```

2020-12-08 17:20 UTC, CohenCyril commented on theories/normedtype.v
> +  (r : {posnum R}) : open_nbhs x (closed_ball x r%:num)^°.
I would remove this lemma and replace it when need by two lemmas:
1. `(closed_ball x r)^° = ball x r` 
2. `r > 0 -> open_nbhs x (ball x r)`

2020-12-08 17:22 UTC, CohenCyril commented on theories/normedtype.v
> +  (r : {posnum R}) : open_nbhs x (closed_ball x r%:num)^°.
BTW, the preferred usage of `{posnum R}` is not to put it as assumption because it is contaminating and we prefer to be able to partially instantiate lemmas with numbers with proofs of positivity...
We phrase it using `forall r, r > 0 -> stuff` and use `=> _/posnumP[r]` in the goal instead, side conditions that are solvable are automatically discharged.

2020-12-08 19:35 UTC, mkerjean commented on theories/normedtype.v
> +  (r : {posnum R}) : open_nbhs x (closed_ball x r%:num)^°.
Do you suggest that `closed_ballE` be rewritten this way too ?

2020-12-08 21:18 UTC, CohenCyril commented on theories/normedtype.v
> +  (r : {posnum R}) : open_nbhs x (closed_ball x r%:num)^°.
sure

2020-12-08 21:18 UTC, CohenCyril commented on theories/normedtype.v
> +  (r : R) : exists e, ball x e `<=` closed_ball x r.
`e` should be non zero or this is trivial.

2020-12-08 21:20 UTC, CohenCyril commented on theories/normedtype.v
> +Qed.
```suggestion
Proof. by move=> x_neq0; rewrite normmZ normfV normr_id mulVf// normr_eq0. Qed.
```

2020-12-18 19:27 UTC, mkerjean commented on theories/normedtype.v
> +(* open_ball *)
I stumble on a loop here : to prove that balls are open I need to use that balls are open ... Why is the interior of `A` defined as the set of points having an *open* neighborhood inside `A`, and not just a neighborhood ? I am used to the second definition, which would allow to prove that balls are open.

2020-12-18 20:33 UTC, mkerjean commented on theories/normedtype.v
> +(* open_ball *)
If there is indeed a loop I would be in favor of not splitting the lemmas as suggested by @CohenCyril above, to merge this PR soonish and open a new one to work on open balls.

2020-12-19 15:22 UTC, CohenCyril commented on theories/normedtype.v
> +(* open_ball *)
There is no loop, here is the proof.
```suggestion
Lemma ball_open (R : numDomainType) (V : normedModType R) (x : V)
      (r : R) : 0 < r -> open (ball x r).
Proof.
move=> r0; rewrite openE /= => y; rewrite -ball_normE /interior /= => Bxy. 
near=> z => /=; rewrite (le_lt_trans (@ler_dist_add _ _ y _ _))//.
by rewrite addrC -ltr_subr_addr; near: z; apply: cvg_dist; rewrite // subr_gt0.
Grab Existential Variables. all: end_near. Qed.
```

An alternative, and potentially shorter, proof would go through the composition of addition and norm.

2020-12-21 10:23 UTC, mkerjean commented on theories/normedtype.v
> +(* open_ball *)
What was the issue with my proof ? Is the use of `nbhsE` problematic ?

2020-12-21 20:02 UTC, mkerjean commented on theories/normedtype.v
> +rewrite /closed_ball /closure /interior. Admitted.
Any help welcomed, I don't know how to prove this with near notations.

2021-01-14 21:18 UTC, mkerjean commented
I addressed all your comments @CohenCyril. It could be ready to be merged - or maybe another look at the proofs is necessary.

2021-01-15 05:15 UTC, affeldt-aist commented
- (*TBA topology.v*) means to be added to topology.v?
  + of course this can't be done right away because the lemmas here depend on ball_normE
  + I observe that nbhs0_lt and nbhs'0_lt could be specialized to V = K^o
- naming suggestions:
  + closed_neigh_ball -> open_nbhs_closed_ball? (because we don't use the string "neigh")
  + sub_closed_ball -> closed_ball_subset? (I think that the full string "subset" is privileged)
  + ball_closed_ball -> subset_closed_ball? (might be easier to guess what the lemma provides)

2021-01-15 12:55 UTC, CohenCyril requested changes
Please update the changelog with the last renamings.
Aside from that we're good to go.

2021-01-15 17:48 UTC, CohenCyril approved these changes
LGTM

2021-01-15 17:48 UTC, merged