Dual ereal
math-comp/analysis pull request #374
Opened 2021-05-04 15:14 UTC by proux01

In Coquelicot, -oo + +oo was defined as 0, which was nice for morphisms with opposite but terrible as addition was not even associative. In ereal.v, the addition adde is such that -oo + +oo = -oo, making it associative an such that (er R, Order.max, adde) is a semiring (the id element -oo of Order.max is a zero for adde). However, sometimes we rather need (er R, Order.min, adde) to be a semiring, with -oo + +oo = +oo. This PR offers that, I don't know if we want it in analysis?

2021-05-04 15:21 UTC, CohenCyril commented
I'd rather keep extended reals a commutative monoid (which was the case before this PR), this is crucial for taking maximal advantage of bigops.

2021-05-04 15:22 UTC, proux01 commented
I fully agree, this PR doesn't change anything about extended reals, just offers dual extended reals where -oo++oo = +oo instead of -oo.

2021-05-04 15:31 UTC, CohenCyril commented
Also, I would integrate it within `ereal`

2021-05-04 16:11 UTC, proux01 commented
> * I cannot foresee a use yet (could you point me towards a concrete example)

We use it in a formalization of Network Calculus (a static analysis for networks, used to certify embedded networks in civil aircrafts) that is based on min-plus algebra. Sorry, can't share the code yet due to licencing issues (hope to finally fix that in the coming weeks).

> * I would not integrate this within the same scope and same names. We could use for example `%dE` (for "dual Extended") an the names could be prefixed with `dual_`?

Would indeed make sense to enable mix use of both regular and dual versions (no idea if that can arise though).

2021-05-04 16:21 UTC, CohenCyril commented
> Would indeed make sense to enable mix use of both regular and dual versions (no idea if that can arise though).

I think it can... and I forgot about providing correspondance lemmas under the negation `add_undef` precondition.
(Although we might very well switch to `add_def` as per #365)

2021-05-05 16:41 UTC, CohenCyril requested changes

2021-05-05 16:41 UTC, CohenCyril commented on theories/ereal.v
> +Notation "x <= y" := (lee x y) (only printing) : ereal_dual_scope.
Notations in the `ereal_dual_scope`  must not take precedence, they should be declared before their `ereal_scope` counterpart. Moreover, I do not see the point unless the variables of the notations are "rescoped" inside `ereal_dual_scope`. I'm also tempted to suggest one definies an alias `dual_ereal := ereal` and uses `Bind Scope` on this type to make sure arguments are correctly scoped.

2021-05-05 16:41 UTC, CohenCyril commented on theories/ereal.v
> +Definition dadde x y :=
For the operators, I'd use a longer name, like `dual_adde`

2021-05-05 16:41 UTC, CohenCyril commented on theories/ereal.v
> +Notation "-%dE"   := oppe.
I do not understand this one, it should a minima be declared before the other one, so as not to take precedence... But I'm not sure how useful this can be...

2021-05-05 16:41 UTC, CohenCyril commented on theories/ereal.v
> +Notation "- x"   := (oppe x) : ereal_dual_scope.
swap not to take precedence, and make sure `x` is correctly scoped

2021-05-05 16:41 UTC, CohenCyril commented on theories/ereal.v
> +Notation "x + y" := (dadde x y) : ereal_dual_scope.
One should make sure `x` and `y` are correctly scoped (same for multiplication etc.)

2021-05-05 16:41 UTC, CohenCyril commented on theories/ereal.v
> +
Missing two compatibility lemmas :
```
Lemma dual_addeE (x y : \bar R) : (x + y)%dE = - ((- x) + (- y))%E.
Lemma dual_sumeE I (r : seq I) (P : {pred I}) (F : I -> \bar R) : (\sum_(i <- r | P i) F i)%dE = - (\sum_(i <- r | P i) - F i)%E.
Lemma def_dual_addeE (x y : \bar R) : ~~ add_undef x y -> (x + y)%dE = (x + y)%E.
```
Then in the remainder of this file, I find that interleaving ereal lemmas with dual ones clutters the code.
I would put all dual lemmas in a single section and prove them all using `dual_addeE` and `dual_sumeE`

2021-05-06 13:35 UTC, proux01 commented on theories/ereal.v
> +
Makes sense, I had to add a few lemmas in order to prove everything by duality but that did work.

2021-05-06 13:37 UTC, proux01 commented on theories/ereal.v
> +Notation "-%dE"   := oppe.
Indeed quite useless, removed.

2021-05-06 15:15 UTC, proux01 commented
@CohenCyril all your comments should be taken into account.

2021-08-13 11:02 UTC, proux01 commented
This is rebased on top of #403, `dual_mule` disappeared since it is now the same as `mule`.

2021-09-28 08:41 UTC, proux01 commented
Just rebased this on top of master now that #403 is merged.

2021-09-29 14:40 UTC, proux01 commented
@CohenCyril all notation seem to work properly (for instance `x + y <= -(x + y))%dE` uses dual_adde as expected and prints back identically), I just spotted an omission int the bigop notations and `+?` was missing in `ereal_dual_scope`.

2021-10-29 23:27 UTC, CohenCyril commented
> @CohenCyril I'd like to rebase this on top of #459 once it is merged (to add lemmas about mine, the dual of maxe)

Sure. I also think that the new convention is to use `forall x : \bar R, x \in fin_num -> P x` rather than `forall r : R, P r%:E`.
I also think theorems about dual ereal should be encapsulated in a submodule and imported on demand.

2021-11-02 16:11 UTC, proux01 commented
Indeed, done, this should now be ready.

BTW, this dual add thing is used there: https://gitlab.mpi-sws.org/proux/nc-coq
I wanted to do opam and nix packages for CI when I realized I'm still using dioid master that relies on a nasty hack to use HB on top of current MC https://github.com/math-comp/dioid/blob/master/HB_wrappers.v . So I should probably wait for MC 2.0.

2021-11-04 16:53 UTC, CohenCyril approved these changes
Ok, thanks!, let's rebase and merge.

2021-11-04 17:06 UTC, proux01 commented
rebased

2021-11-04 17:53 UTC, merged

2021-11-05 07:42 UTC, proux01 commented
Thanks!