Change the definition of is_interval to rely on large inequalities
math-comp/analysis pull request #411
Opened 2021-07-29 14:08 UTC by ybertot

The previous definition, based on strict inequalities, is less practical

The impact of this change has been tested against two other pull requests that use the `is_interval` concept

- #385 : porting this PR leads to branch [ctinv-itv](https://github.com/ybertot/analysis/tree/ctinv-itv)
- #371 : porting this PR leads to branch [ctv-itv-meas](https://github.com/ybertot/analysis/tree/ctv-itv-meas) (actually this branch contains both 385 and 371).

2021-07-29 15:34 UTC, CohenCyril commented
Hi @ybertot, I do not understand what 793badc are 3aa4fe5 doing here. Did I miss something?

2021-07-30 06:19 UTC, ybertot commented
I don't understand either.  I did a rebase, and all of a sudden these commits were included in the branch.  Maybe I goofed one of my rebase, and then I had to do force push, but people usually have to do a force push after a rebase, so that you are really working without a safety net at this point.

Maybe the solution will be to remake the branch from scratch and cherry-pick the commits.  I am not too fluent, but I may be able to repair that.

2021-07-30 07:50 UTC, CohenCyril commented
> I did a rebase, and all of a sudden these commits were included in the branch.

Well, it looks like you rebased master on top of `is_itv` and then added a commit...

2021-07-30 08:18 UTC, ybertot commented
should be fixed now.

2021-07-30 08:41 UTC, CohenCyril approved these changes
OK, I'm 100% of the benefits of this change.
@affeldt-aist do you agree?

2021-07-30 08:52 UTC, affeldt-aist commented
> OK, I'm 100% of the benefits of this change.
> @affeldt-aist do you agree?

Yes, no problem.

2021-07-30 10:27 UTC, CohenCyril requested changes
nitpicking

2021-07-30 10:27 UTC, CohenCyril commented on theories/normedtype.v
> +    rewrite !le_eqVlt => /orP [/eqP <- // | xz] /orP[/eqP -> // | zy] Ez.
```suggestion
    rewrite !le_eqVlt => /predU1P [<-//|xz] /predU1P[/eqP->|zy] Ez.
```

2021-07-30 10:27 UTC, CohenCyril commented on theories/normedtype.v
> +by rewrite (ltW yr) (ltW er).
```suggestion
by rewrite addrCA subrr addr0 => er; apply: (iX e y); rewrite ?ltW.
```

2021-07-30 10:27 UTC, CohenCyril commented on theories/normedtype.v
> +by rewrite (ltW yr) (ltW re).
```suggestion
by rewrite opprB addrCA subrr addr0 => re; apply: (iX y e); rewrite ?ltW.
```

2021-07-30 10:27 UTC, CohenCyril commented on theories/normedtype.v
> +by apply: (iX _ _ Xy Xz); rewrite (ltW xy) (ltW xz).
```suggestion
by apply: (iX y z); rewrite ?ltW.
```

2021-07-30 10:27 UTC, CohenCyril commented on theories/normedtype.v
> +by apply (iE _ _ Ex Ey); rewrite xz.
```suggestion
  by move=> xz zy; apply: (iE x y); rewrite ?ltW.
rewrite !le_eqVlt => /predU1P[<-//|xz] /predU1P[->//|zy].
by apply: (iE x y); rewrite ?xz.
```

2021-07-30 10:27 UTC, CohenCyril commented on theories/normedtype.v
> +by rewrite (ltW er) (ltW rf).
```suggestion
by rewrite opprB addrCA subrr addr0 => rf; apply: (iX e f); rewrite ?ltW.
```

2021-07-30 10:27 UTC, CohenCyril commented on theories/normedtype.v
> +     apply sup_ub; first by exists y => u [_] /andP[].
```suggestion
    apply/negP; rewrite -leNgt.
    apply: sup_ub; first by exists y => u [_] /andP[].
```

2021-09-28 12:16 UTC, CohenCyril approved these changes
LGTM

2021-09-28 14:31 UTC, merged