fixes #613
math-comp/analysis pull request #624
Opened 2022-04-01 02:42 UTC by affeldt-aist

##### Motivation for this change

fixes #613

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`
~~- [ ] added corresponding documentation in the headers~~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

2022-04-25 13:51 UTC, affeldt-aist commented
Since it is essentially a renaming discussed in the meeting, we may consider it as good to go?

2022-04-30 02:12 UTC, affeldt-aist commented
@ybertot ping?

2022-05-02 13:22 UTC, ybertot requested changes
This looks good to me.  There are two minor problems that I think should be corrected.

2022-05-02 13:22 UTC, ybertot commented on theories/lebesgue_integral.v
> +Lemma integrable_funenego f : integrable f -> integrable f^\-.
I believe there is typo here: should funeneg

2022-05-02 13:22 UTC, ybertot commented on CHANGELOG_UNRELEASED.md
> +  + `integrable_funenng` -> `integrable_funepos`
The renaming of `integrable_funennp` into `integrable_funeneg` should also be documented.

2022-05-02 14:12 UTC, affeldt-aist commented
> This looks good to me. There are two minor problems that I think should be corrected.

Indeed. Thank you!

2022-05-02 14:54 UTC, merged