inv_cvg
math-comp/analysis pull request #772
Opened 2022-10-13 01:14 UTC by affeldt-aist

##### Motivation for this change

needed to develop measure theory

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`
- [ ] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

2022-10-13 03:46 UTC, zstone1 approved these changes

2022-10-14 15:29 UTC, CohenCyril requested changes
@affeldt-aist the name was clearly too general `inv_cvg` was far too ambiguous (note that `cvgV` also exist). I gave a suggestion.
I added a few missing helper lemmas, however like many lemmas here, they could and should actually be generalized to filters rather than mere sequences.

2022-10-16 10:12 UTC, CohenCyril commented
Also the condition `u i > 0` could be restricted to "near `\oo`"

2022-10-17 10:49 UTC, CohenCyril commented on theories/sequences.v
> +  u_ --> +oo <-> (forall A, \forall n \near \oo, A%:E <= u_ n).
This is actually neither a generalization nor a weakening. The following are all equivalent:
1. `u --> +oo`
2. `forall A, \forall n \near \oo, A%:E <= u_ n`
3. `\forall A \near +oo, \forall n \near \oo, A%:E <= u_ n`

When faced with 1.:
- as a goal it's actually better to turn it into 3., then you can use `near=> A` and assume `A` to be as large as you need.
- but as an hypothesis, it's better to get 2., so you can apply it to anything without any constraint on `A`

2022-10-17 10:50 UTC, CohenCyril commented on theories/sequences.v
> +  u_ --> +oo <-> (forall A, \forall n \near \oo, A%:E <= u_ n).
Maybe we should actually write it
```suggestion
  [<-> u_ --> +oo,
         forall A, \forall n \near \oo, A%:E <= u_ n &
         \forall A \near +oo, \forall n \near \oo, A%:E <= u_ n ]
```
?

2022-10-17 10:52 UTC, CohenCyril commented on theories/sequences.v
> +Unshelve. all: by end_near. Qed.
Rewrite with `[<-> ..., ... ]` and merge with `cvgPpinfty_lt_near` ?

2022-10-17 10:53 UTC, CohenCyril commented on theories/sequences.v
> +Unshelve. all: by end_near. Qed.
And the same for everything here?

2022-10-18 16:32 UTC, CohenCyril commented
It seems that I hijacked this PR.

2022-10-18 16:34 UTC, CohenCyril commented
@affeldt-aist I will move my changes to another PR. I'll truncate this one at e61b452d0b7f2b099911c823dfac40c2585adb65 and merge

2022-10-18 16:37 UTC, CohenCyril commented
Opened https://github.com/math-comp/analysis/pull/780

2022-10-18 16:47 UTC, CohenCyril commented
Rebased

2022-10-18 16:47 UTC, CohenCyril approved these changes

2022-10-18 16:48 UTC, CohenCyril commented
Rebase, merge when CI passes

2022-10-18 17:06 UTC, merged