bigmax for ereals
math-comp/analysis pull request #779
Opened 2022-10-18 02:39 UTC by affeldt-aist

Co-authored-by: IshiguroYoshihiro
Co-authored-by: Takafumi Saikawa <tscompor@gmail.com>

##### Motivation for this change

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`
~~- [ ] added corresponding documentation in the headers~~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

2022-10-18 08:24 UTC, proux01 commented on theories/constructive_ereal.v
> +  \big[maxe/-oo]_(j < n) F j <= \big[maxe/-oo]_(j < m) F j.
Can't we get something more generic like
```suggestion
Lemma lee_bigmax_seq (I : eqType) s s' P P' (F : I -> \bar R) :
  {subset [seq i <- s | P i] <= [seq i <- s' | P' i]} ->
  \big[maxe/-oo]_(i <- s | P i) F i <= \big[maxe/-oo]_(i <- s' | P' i) F i.
```
from which this would be derived? (it should also probably have a P (which would be predT in trivial cases))

We could also have lee_bigmax_nat while at it

And similar lemmas for mine

2022-10-19 07:56 UTC, affeldt-aist commented on theories/constructive_ereal.v
> +  \big[maxe/-oo]_(j < n) F j <= \big[maxe/-oo]_(j < m) F j.
I addressed the easy part of your comment but not the generalization to `seq`.

2022-10-20 12:35 UTC, CohenCyril commented on theories/constructive_ereal.v
> +  \big[maxe/-oo]_(j < n | P j) F j <= \big[maxe/-oo]_(j < m | P j) F j.
Isn't it a generic lemma for ordered types with a bottom element?

2022-10-20 12:38 UTC, proux01 commented on theories/constructive_ereal.v
> +  \big[maxe/-oo]_(j < n | P j) F j <= \big[maxe/-oo]_(j < m | P j) F j.
I think we don't even need the bottom element. I'm having a look.

2022-10-21 13:34 UTC, proux01 commented on theories/constructive_ereal.v
> +  \big[maxe/-oo]_(j < n | P j) F j <= \big[maxe/-oo]_(j < m | P j) F j.
Sorry for the delay, this can indeed be generalized to ordered types. Done and put more general lemma in mathcomp_extra.v. Once this is merged, I should do a backporting PR on mathcomp.

2022-10-21 14:01 UTC, CohenCyril approved these changes
Ok that's great, could you also backport this to mathcomp?

2022-10-21 14:03 UTC, proux01 commented
> Ok that's great, could you also backport this to mathcomp?

Sure
I still have some doubts about the order of arguments in `le_bigmax_ord` and the genericity with respect to the condition P, let me see if I can improve that before merging here.

2022-10-21 16:04 UTC, proux01 commented
@CohenCyril I uniformized the order of arguments and put the widening of range and condition in orthogonal lemmas.

CI green, I think this can be merged (I'll then open a backporting PR on mathcomp).

2022-10-21 16:17 UTC, CohenCyril commented on classical/mathcomp_extra.v
> +Qed.
It would make sense to have versions of the other lemmas including the weakening of the predicate...
Of course it's juste a combination via transitivity (although one should do it with the smallest sequence / range / ordinal / set)

2022-10-21 16:19 UTC, CohenCyril commented on classical/mathcomp_extra.v
> +
What about `le_bigmax_in` 
```coq
\big[max/x0]_(i in A | P i) F i <= \big[max/x0]_(i in A | P i) F i.
```
(which is a weakening of `le_bigmax_condW`)

2022-10-21 16:20 UTC, CohenCyril commented on classical/mathcomp_extra.v
> +Lemma le_bigmax_condW x0 (I : eqType) s (P P' : pred I) (F : I -> T) :
Is the `W` necessary? (to avoid a conflict for example?), if not we could just remove it
```suggestion
Lemma le_bigmax_cond x0 (I : eqType) s (P P' : pred I) (F : I -> T) :
```

2022-10-23 17:31 UTC, proux01 commented on classical/mathcomp_extra.v
> +
I guess
```
\big[max/x0]_(i in A | P i) F i <= \big[max/x0]_(i in A | P' i) F i.
```
Done

2022-10-24 08:21 UTC, CohenCyril requested changes
So I'm pretty happy with the current state, except a few things that I'm going to make suggestions for very soon.

2022-10-24 08:40 UTC, CohenCyril commented on classical/mathcomp_extra.v
> +Lemma le_bigmax_condW x0 (I : eqType) s (P P' : pred I) (F : I -> T) :
> Unfortunately, there is already a
> 
> ```
> Lemma le_bigmax_cond j P F : P j -> F j <= \big[max/x]_(i | P i) F i.
> ```
> 
> (not yet backported to mathcomp though, it would then be pretty easy to change)

given that `leq_bigmax_cond` is already in mathcomp, it's not a good idea to change it.

2022-11-07 15:15 UTC, CohenCyril commented
> @CohenCyril ping?

Got sidetracked, posting soon

2022-11-10 15:29 UTC, proux01 commented
@CohenCyril not fond of the option business, sure it is convenient here but I think the best solution would be to add semigroups in the monoid hierarchy as done in the HB port of mathcomp. Adding semigroups will make all `_AC` lemmas disappear. Meanwhile, the use of `oAC` and `big_ACE` tend to reverse the dependency between the corresponding monoid and semigroup lemmas.

Otherwise, looks good to me, I particularly like the generalization to increasing operators.

2022-11-12 17:14 UTC, CohenCyril commented
> @CohenCyril not fond of the option business, sure it is convenient here but I think the best solution would be to add semigroups in the monoid hierarchy as done in the HB port of mathcomp. Adding semigroups will make all `_AC` lemmas disappear. Meanwhile, the use of `oAC` and `big_ACE` tend to reverse the dependency between the corresponding monoid and semigroup lemmas.

I agree with you that the "option buisness" is not useful in a context where mathcomp law hierarchy is generalize to  semigroups. However you already extended mathcomp with the `_AC` lemmas so I did not feel the need to reprove them here and and I went for the shortcut of `oAC` to import the few required ones here in `mathcomp_extra`, and these specific proofs will disapear as soon as `mathcomp 1.16` is required for mathcomp analysis.

Meanwhile, the `oAC` buisness is not strictly necessary but it's a fun example of left adjoint to the forgetful functor from monoids to semigroups, how it can be used to derive theory from a more powerful one and could be very useful in a context where a monoid is really needed... Hence I advise to port it to mathcomp but not to port the proofs that I did to generalize results from monoid to semigroups, but to keep the ones you already did in mathcomp master...

2022-11-12 17:29 UTC, proux01 commented
Ok, let's go for that solution. If you are happy with the current state, I let you approve the PR and I'll merge it by the end of the week. I'll then be able to do the backporting to mathcomp.

2022-11-12 19:18 UTC, CohenCyril approved these changes

2022-11-17 14:14 UTC, merged