rename theories/set_interval to avoid dup
math-comp/analysis pull request #784
Opened 2022-10-21 06:14 UTC by affeldt-aist

##### Motivation for this change

It appears that `set_interval.v` was also duplicated in two directories.
(Also fixes a documentation problem: the header from `set_interval.v`e
needed to move to `classical`.)

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`
- [x] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

2022-10-21 10:33 UTC, CohenCyril approved these changes

2022-10-21 10:35 UTC, CohenCyril commented
You also need to update the `Make` files

2022-10-21 10:35 UTC, CohenCyril requested changes
You also need to adapt the `Make` files

2022-10-21 10:38 UTC, affeldt-aist commented
> You also need to adapt the `Make` files

We'll do asap.

2022-10-21 13:08 UTC, proux01 commented
Done, I also added the missing entries in CHANGELOG_UNREALEASED.md, thanks for the fix.

2022-10-26 05:21 UTC, affeldt-aist commented
There seem to be two kinds of errors in the CI:
- "No rule to make target 'real_interval.v', needed by '.Makefile.coq.d'" (the renamed file)
- "Error: Unable to local library boolp" when processing `classical_sets.v`

2022-10-26 08:12 UTC, proux01 commented
> There seem to be two kinds of errors in the CI:

@affeldt-aist sorry, I messed up the Makefile, CI green now.

2022-10-26 08:41 UTC, merged