measurable_fun_if
math-comp/analysis pull request #788
Opened 2022-10-28 07:14 UTC by affeldt-aist

##### Motivation for this change

This lemma has found a use in PR #749 and in PR #769 so it is maybe worth integrating master.

@t6s @hoheinzollern 

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`
- [x] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

2022-11-04 14:30 UTC, zstone1 requested changes
The condition `measurable_fun setT f` is too strong. The suggestions should weaken it to `measurable_fun D f`, which is somewhat stronger.

2022-11-04 14:30 UTC, zstone1 commented on theories/measure.v
> +    (f : T1 -> bool) (mf : measurable_fun setT f) :
```suggestion
    (f : T1 -> bool) (mf : measurable_fun D f) :
```

2022-11-04 14:30 UTC, zstone1 commented on theories/measure.v
> +  by have := mf measurableT [set true]; rewrite setTI; exact.
```suggestion
have mDf : measurable (D `&` [set b | f b]) by exact: mf.
```

2022-11-04 14:30 UTC, zstone1 commented on theories/measure.v
> +  by have := mf measurableT [set false]; rewrite setTI; exact.
```suggestion
have mDNf : measurable (D `&` f @^-1` [set false]) by exact: mf.
```

2022-11-10 06:14 UTC, affeldt-aist commented on theories/measure.v
> +    (f : T1 -> bool) (mf : measurable_fun setT f) :
Indeed. I push it in a next commit with a shorter proof.

2022-11-10 13:41 UTC, zstone1 approved these changes

2022-11-13 03:43 UTC, merged