Draft: Introduce conves
math-comp/analysis pull request #794
Opened 2022-11-04 06:51 UTC by yoshihiro503

Co-authored-by: Reynald Affeldt <reynald.affeldt@aist.go.jp>

##### Motivation for this change

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`
  (do not edit former entries, only append new ones, be careful:
   merge and rebase have a tendency to mess up `CHANGELOG_UNRELEASED.md`)
- [ ] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

2022-12-02 22:55 UTC, zstone1 requested changes
Nice results. I've made comments about a couple generalizations, one regarding annoying endpoint issues, the other regarding generalizing to vector space ranges. I care more about the endpoints one mostly because it's much harder to fix later. Happy to work with you on that if that'd be helpful.

2022-12-02 22:55 UTC, zstone1 commented on theories/convex.v
> +  forall x, x \in `[a, b] -> derivable f x 1.
This definition misbehaves at the endpoints. In particular, it requires `f` to be be "differentiable from the left at `a`". That makes this definition rely on values of `f` outside `[a,b]`. One big consequence is characteristic functions like ``if x \in `[a,b] then 1 else 0`` fails this definition, as its not derivable at `a` or `b`. For what it's worth, I had an analogous issue with `realfun.v`, see #752 for how I addressed it there. You'll need something slightly different here, though.

I've seen textbooks take these approaches:
1. Demanding "continuity up the endpoints" is one approach
```
forall x, x \in `]a, b[ -> derivable f x 1.
/\
cvg (at_right a f^`()) /\ cvg (at_right b f^`())
```
or some variation of this. However, this implies some continuity of the derivative, which is maybe not ideal.
2. We could change the derivative to use a different topology. One way to do that is add an analog to the ``{within `[a,b], continuous f}`` notation of  ``{within `[a,b], derivable f}``. This would take limits only on the subspace topology. 
3. Similarly, but specialized to working in `R`, it should be fine to define it like
```
forall x, x \in `]a, b[ -> derivable f x 1
/\
"differentiable from the right at b" /\ "differentiable from the left at a"
```
For some sensible notion of "left" and "right" derivative.

2022-12-02 22:55 UTC, zstone1 commented on theories/convex.v
> +Variables (f : R -> R) (a b : R).
Where do we need the assumption that the range of `f` is `R`? If it's painless, generalizing to a vector space would be quite helpful for me. I'll need some stuff about convexity in both `R` and `R^n` for my work on space-filling curves, so I'm happy to have these results either way.

2023-03-13 17:24 UTC, affeldt-aist commented
I opened PR #873 and moved the comments by @zstone1 there because it looked like maintainers do not have write access (not 100% sure though). I hope you don't mind moving the conversation there.

2023-04-20 10:30 UTC, closed without merging