adjust deprecated notes
math-comp/analysis pull request #798
Opened 2022-11-13 08:35 UTC by affeldt-aist

##### Motivation for this change

Some deprecated notes seemed to refer to older namings.

##### Things done/to do

~~- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`~~
~~- [ ] added corresponding documentation in the headers~~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

2022-11-14 23:42 UTC, CohenCyril requested changes
Good job at spotting this! The changelog must be fixed accordingly.

2022-11-14 23:42 UTC, CohenCyril commented on theories/normedtype.v
> -  note="use `cvg_dist_lt` or a variation instead")]
Yes you are right

2022-11-14 23:42 UTC, CohenCyril commented on theories/normedtype.v
> +  note="use `fcvgrPdist_lt` or a variation instead")]
No, that was correct, I want to encourage the use of `cvgrPdist_lt` instead.

2022-11-14 23:42 UTC, CohenCyril commented on theories/normedtype.v
> +  note="use `cvgrPdist_le` or a variation instead")]
Yes, you are right

2022-11-14 23:42 UTC, CohenCyril commented on theories/normedtype.v
>  Lemma cvg_dist2 {F : set (set U)} {G : set (set V)}
No, I really meant `cvgr_dist_lt2` why did you think otherwise?

2022-11-14 23:42 UTC, CohenCyril commented on theories/normedtype.v
> +note="use `fcvgr_dist_lt2P` or a variant instead")]
No, that was correct, I want to encourage the use of `cvgr_dist_lt2P` instead.
However the latter and all the `2` family should actually be renamed `cvgr2Pdist_lt` and so on...

2022-11-14 23:42 UTC, CohenCyril commented on theories/sequences.v
> +  note="use `cvgNrNy` instead")]
Yes good catch!

2022-11-15 00:01 UTC, affeldt-aist commented on theories/normedtype.v
>  Lemma cvg_dist2 {F : set (set U)} {G : set (set V)}
I was actually wondering since this very proof is actually using `cvgr_dist_lt2P` even though it is not essential.

2022-11-17 14:17 UTC, CohenCyril commented on CHANGELOG_UNRELEASED.md
> +  + `cvg2dist` (use `cvgr2dist_lt` or a variant instead),
```suggestion
  + `cvg_dist2P` (use `cvgr2dist_ltP` or a variant instead),
  + `cvg_dist2` (use `cvgr2dist_lt` or a variant instead),
```

2022-11-23 17:55 UTC, merged