minor fixes and additions to `exp.v`
math-comp/analysis pull request #939
Opened 2023-06-01 02:44 UTC by affeldt-aist

##### Motivation for this change

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [x] added corresponding documentation in the headers

##### Compatibility with MathComp 2.0

- [x] I added the label `TODO: HB port` to make sure someone ports this PR to
      the `hierarchy-builder` branch **or** I already opened an issue or PR (please cross reference).

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) and put a milestone if possible.

2023-06-22 14:13 UTC, zstone1 requested changes
Just one confusing lemma statement. If adding a `x!=0` condition breaks too many things, at least making the coercion explicit will make it more readable for me.

2023-06-22 14:13 UTC, zstone1 commented on theories/exp.v
> +Lemma power_pos0 x : 0 `^ x = (x == 0)%:R.
Everything about this statement is uncomfortable. The fact that we have a theorem that explicitly relies on `0 ^ 0` behavior is awkward. And this uses the most surprising coercion, `nat_of_bool`. I see that this lemma gets used a bunch. But would `x != 0 -> 0^x = 0` work in its place?

2023-06-28 05:09 UTC, affeldt-aist commented on theories/exp.v
> +Lemma power_pos0 x : 0 `^ x = (x == 0)%:R.
Indeed, it looks a bit too ssreflectish. Changing to the format you propose reduces the size of scripts a bit (see the last commit) so if moreover the statement is more readable this is a goof change.

2023-06-28 13:37 UTC, zstone1 approved these changes

2023-06-29 02:53 UTC, merged